account/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import url
from django.urls import path, include
from django.views.generic import TemplateView

from . import views
from .consumers import ChatMessagesConsumer

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('delete_message/<int:message_id>', views.delete_message, name='delete_message'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile_create/', views.create_profile, name='profile_create'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('profile_guest/<slug:slug>', views.profile_guest, name='profile_guest'),
    path('logout/', views.logout_view, name='logout'),
    path('send_friend/<slug:slug>', views.send_friend_request, name='send_friend'),
    path('accept_friend/<slug:slug>', views.accept_friend, name='accept_friend'),
    path('', views.chat, name='indsex'),
    path(r'^dialogs/$', login_required(views.DialogsView.as_view()), name='dialog'),
    path(r'^dialogs/(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messages'),
    path(r'^dialogs/create/(?P<user_id>\d+)/$', login_required(views.CreateDialogView.as_view()), name='create_dialog'),

]

old_toon/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('toons/', include('toons.urls', namespace='toons')),
    path('account/', include('account.urls', namespace='account')),
    path('subscription/', include('subscribe_payment.urls', namespace='subscribe_payment')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toons/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, toons_detail, toons_series, get_streaming_video, category_detail, like, favorite, review, like_review, review_update,review_delete

app_name = 'toons'

urlpatterns = [
    path('', index, name='index'),
    path('<slug:slug>/', toons_detail, name='toons_detail'),
    path('series/<int:pk>/', toons_series, name='toonseries_detail'),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('toonserie/<int:pk>/', get_streaming_video, name='toonseries_detaisl'),
    path('like/<slug:slug>/', like, name='like'),
    path('favorite/<slug:slug>/', favorite, name='favorite'),
    path('review/<slug:slug>/', review, name='review'),
    path('review_likes/<int:review_id>/', like_review, name='review_like'),
    path('review_update/<int:review_id>/', review_update, name='review_update'),
    path('review_delete/<int:review_id>/', review_delete, name='review_delete'),



]

toons/models.py
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models import Avg
import random
import string
from subscribe_payment.models import lvl_subscribe

User = get_user_model()
from django.urls import reverse


#создание случайного имени
def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))

#класс категории
class category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = rand_slug()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('toons:category_detail', kwargs={'slug': self.slug})
class authors(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = rand_slug()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def get_absolute_url(self):
        return reverse('toons:author_detail', kwargs={'slug': self.slug})
class genre(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = rand_slug()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def get_absolute_url(self):
        return reverse('toons:genre_detail', kwargs={'slug': self.slug})
class Review_review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=2000)
    likes = models.ManyToManyField(to=User, related_name='review_review_likes', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def likes_count(self):
        return self.likes.count()
    def unlike(self, user):
        self.likes.remove(user)
    def like(self, user):
        self.likes.add(user)

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    likes = models.ManyToManyField(to=User, related_name='review_likes', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    otvet = models.ManyToManyField(Review_review, related_name='reviews', blank=True)

    def likes_count(self):
        return self.likes.count()
    def unlike(self, user):
        self.likes.remove(user)
    def like(self, user):
        self.likes.add(user)


#класс мультиков)(()()))
class toons_model(models.Model):
    genre = models.ForeignKey(genre, on_delete=models.CASCADE, verbose_name='Жанр', blank=True, null=True)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    author = models.ForeignKey(authors, on_delete=models.CASCADE, verbose_name='Автор', blank=True, null=True)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='toons', blank=True, default='1670311516_61-fashionhot-club-p-termobele-skins-64.jpg')
    rating = models.FloatField(default=0.0, blank=True)
    year_created = models.DateField(null=True, blank=True)
    is_published = models.BooleanField(default=True)
    views = models.IntegerField(default=0)  # Новое поле для просмотров
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(to=User, related_name='toon_likes', blank=True, default='alex')
    favourites = models.ManyToManyField(to=User, related_name='favourites', blank=True)
    reviews = models.ManyToManyField(to=Review, related_name='reviews', blank=True)
    subing = models.ForeignKey(lvl_subscribe, on_delete=models.DO_NOTHING, related_name='subing', blank=True, null=True)

    def reviews_cycle(self):
        return self.reviews.order_by('-created_at')

    def get_rating(self):
        return self.reviews.aggregate(Avg('rating'))['rating__avg']


    def favourite(self, user):
        self.favourites.add(user)

    def unfavourite(self, user):
        self.favourites.remove(user)

    def like(self, user):
        self.likes.add(user)

    def unlike(self, user):
        self.likes.remove(user)

    def likes_count(self):
        return self.likes.count()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = rand_slug()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Мультик'
        verbose_name_plural = 'Мультики'

    def increase_views(self):
        self.views += 1
        self.save()

    # Логика для увеличения просмотров при посещении страницы
    def visit(self):
        self.increase_views()

    def get_absolute_url(self):
        return reverse('toons:toons_detail', kwargs={'slug': self.slug})


class toon_series(models.Model):
    toon = models.ForeignKey(toons_model, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    video = models.FileField(upload_to='video/', validators=[FileExtensionValidator(allowed_extensions=['mp4'])], blank=True, default='1670311516_61-fashionhot-club-p-termobele-skins-64.jpg', null=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)
    description = models.TextField(blank=True, null=True)
    year_created = models.DateField(null=True, blank=True)
    is_published = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = rand_slug()
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Серия'
        verbose_name_plural = 'Серии'

toons/forms.py
from django import forms
from django.forms import ModelForm
from .models import toons_model, Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получите текущего пользователя
        super(ReviewForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user  # Установите текущего пользователя в качестве начального значения
            self.fields['user'].widget = forms.HiddenInput()  # Скрыть поле пользователя в форме

    def save(self, commit=True):
        user = super(ReviewForm, self).save(commit=False)
        if commit:
            user.save()
        return user

class UpdateReview(ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получите текущего пользователя
        super(UpdateReview, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user  # Установите текущего пользователя в качестве начального значения
            self.fields['user'].widget = forms.HiddenInput()  # Скрыть поле пользователя в форме

    def save(self, commit=True):
        user = super(UpdateReview, self).save(commit=False)
        if commit:
            user.save()
        return user

toons/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .services import open_file
from django.http import StreamingHttpResponse
from .models import toons_model, category, toon_series, genre, Review, authors, Review_review
from .filters import BookFilter
from account.models import chat_messages, notification, Profile
from subscribe_payment.models import lvl_subscribe

User = get_user_model()
from .forms import ReviewForm, UpdateReview


def index2(request):
    return render(request, 'shablon/base_index.html')

@login_required(login_url='account:login')
def review(request, slug):
    toon = get_object_or_404(toons_model, slug=slug)
    if request.method == 'POST':
        form = ReviewForm(request.POST, user=request.user)
        if form.is_valid():
            review = form.save(commit=False)
            review.toon = toon
            review.save()
            toon.reviews.add(review)
            return redirect('toons:index')
    else:
        form = ReviewForm(user=request.user)
    return render(request, 'toons/review.html', {'form': form, 'toon': toon})


def index(request):
    messages = chat_messages.objects.all()
    f = BookFilter(request.GET, queryset=toons_model.objects.all())
    genres = genre.objects.all()
    categorys = category.objects.all()
    notifications = notification.objects.filter(for_user=request.user)

    if 'reset' in request.GET:
        f = BookFilter(queryset=toons_model.objects.all())
        toons = f.qs  # Обновление toons при сбросе фильтрации
    else:
        toons = f.qs

    return render(request, 'shablon/base_index.html', {'filter': f, 'genres': genres, 'toons': toons, 'categorys': categorys, 'messages': messages, "notifications": notifications})



def category_detail(request, slug):
    f = BookFilter(request.GET, queryset=toons_model.objects.all())
    genres = genre.objects.all()
    authorss = authors.objects.all()
    categories = category.objects.get(slug=slug)
    if 'reset' in request.GET:
        f = BookFilter(queryset=toons_model.objects.all())
        toons = f.qs.filter(category=categories)  # Обновление toons при сбросе фильтрации
    else:
        toons = f.qs.filter(category=categories)

    return render(request, 'toons/category_detail.html', {'categories': categories, 'toons': toons, 'genres': genres, 'filter': f, 'authors': authorss})
def toons_detail(request, slug):
    toon = toons_model.objects.all().get(slug=slug)
    profile = request.user.profile.sub

    if request.user.is_authenticated:
        toon.visit()
        if toon.subing == profile or toon.subing == None:
            try:
                toon_ser = toon_series.objects.get(toon=toon, is_published=True)
            except toon_series.DoesNotExist:
                return render(request, 'toons/404.html')
            return render(request, 'toons/toon_detail.html', {'toon': toon, 'toon_ser': toon_ser,})
        else:
            return render(request, 'toons/404.html')
    else:
        return redirect('account:login')
def like_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    profile = request.user.profile
    if request.user in review.likes.all():
        # User has already liked the review, remove the like
        profile.likes_reviews.remove(review)
        review.like(request.user)  # Implement the method to remove the like
        request.user.review_likes.remove(review)

    else:
        # User has not liked the review, add the like
        review.like(request.user)  # Implement the method to add the like
        request.user.review_likes.add(review)
        profile.likes_reviews.add(review)
    return redirect('toons:index')  # Redirect to a specific page after liking the review

def review_update(request, review_id):
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    if request.method == 'POST':
      form = UpdateReview(request.POST, instance=review)
      if form.is_valid():
        form.save()
        return redirect('toons:index')
    else:
      form = UpdateReview(instance=review, user=request.user)
    return render(request, 'toons/review_update.html', {'form': form, 'review': review})

def review_delete(request, review_id):
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    review.delete()
    return redirect('toons:index')
def toons_series(request, pk):
    toon_ser = toon_series.objects.get(pk=pk)

    return render(request, 'toons/toon_series.html', {'toon_ser': toon_ser})

def get_streaming_video(request, pk: int):
    video, status_code, content_length, content_range = open_file(request, pk)
    response = StreamingHttpResponse(video, status=status_code, content_type='video/mp4')

    response['Accept-Ranges'] = 'bytes'
    response['Content-Length'] = str(content_length)
    response['Cache-Control'] = 'no-cache'
    response['Content-Range'] = content_range
    return response
def like(request, slug):
    toon = get_object_or_404(toons_model, slug=slug)
    if request.user in toon.likes.all():
        toon.like(request.user)
        request.user.toon_likes.remove(toon)  # Добавить toon в лайки пользователя
    else:
        toon.like(request.user)
        request.user.toon_likes.add(toon)  # Добавить toon в лайки пользователя
    return redirect('toons:index')


def favorite(request, slug):
    toon = get_object_or_404(toons_model, slug=slug)

    # Assuming profile is related to User through a OneToOneField named 'profile'
    profile = request.user.profile

    if request.user in toon.favourites.all():
        toon.unfavourite(request.user)
        request.user.favourites.remove(toon)  # Remove the toon from the user's favorites
        profile.favorites.remove(toon)  # Remove the toon from the user's profile favorites
    else:
        toon.favourite(request.user)
        request.user.favourites.add(toon)  # Add the toon to the user's favorites
        profile.favorites.add(toon)  # Add the toon to the user's profile favorites

    return redirect('toons:index')

def like(request, slug):
    toon = get_object_or_404(toons_model, slug=slug)

    # Assuming profile is related to User through a OneToOneField named 'profile'
    profile = request.user.profile

    if request.user in toon.favourites.all():
        toon.unlike(request.user)
        request.user.toon_likes.remove(toon)  # Remove the toon from the user's favorites
        profile.likes_for.remove(toon)  # Remove the toon from the user's profile favorites
    else:
        toon.like(request.user)
        request.user.toon_likes.add(toon)  # Add the toon to the user's favorites
        profile.likes_for.add(toon)  # Add the toon to the user's profile favorites

    return redirect('toons:index')

toons/templates/toons/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
213
</body>
</html>

toons/templates/toons/category_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <form method="get">
        <ul>
            {% for genre in filter.form.genre %}
            <li>

                    {{ genre }}

            </li>
            {% endfor %}
        </ul>
        <button type="submit" class="button">Применить фильтр</button>
        <button type="submit" class="button" name="reset" value="1">Сбросить фильтр</button>
    </form>

    <ul>
{% for toon in toons %}
<h3>{{  toon.name }}</h3>
<p>{{  toon.description }}</p>
<img src="{{ toon.image.url }}" alt="">
<a href="{{ toon.get_absolute_url }}">About</a>
{% endfor %}

</body>
</html>

toons/templates/toons/genre_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{{ genres.get_absolute_url }}">{{ genres.name }}</a>


</body>
</html>

toons/templates/toons/review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">{% csrf_token %}{{ form.as_p }}<input type="submit"></form>
</body>
</html>

toons/templates/toons/review_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">{% csrf_token %}{{ form.as_p }}<input type="submit"></form>
</body>
</html>

toons/templates/toons/toon_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/reviews/'
        );

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    $(document).ready(function() {

            $('#send').click(function() {
                var review = $('#review_input').val();
                var toon = $('#send').val();
                chatSocket.send(JSON.stringify({
                    'review': review,
                    'toon': toon
                }));
                $('#review_input').val('');
            });

            $('#review_input').keyup(function(e) {
                if (e.keyCode === 13) {
                    $('#send-btn').click();
                }
            });

    });
     $(document).ready(function() {

            $('#send_review').click(function() {
                var comment = $('#review_input2').val();
                var review_id = $('#send_review').val();
                chatSocket.send(JSON.stringify({
                    'comment': comment,
                    'review_id': review_id
                }));
                $('#review_input2').val('');
            });

            $('#review_input2').keyup(function(e) {
                if (e.keyCode === 13) {
                    $('#send_review-btn').click();
                }
            });

    });

</script>
<body>
{{toon}}

<a href="{% url 'toons:like' toon.slug %}">32423</a>
<a href="{% url 'toons:favorite' toon.slug %}">32423</a>
<a href="{% url 'toons:review' toon.slug %}">review</a>
<h3>{{  toon_ser.name }}</h3>
<a href="{% url 'toons:toonseries_detail' toon_ser.id %}">222</a>
<div>

{% for review in toon.reviews.all %}
    <div style="border: 1px solid black;">
    <a href="{% url 'account:profile_guest' review.user.profile.slug %}">{{review.user.profile}}</a>
    <p>{{ review.user.profile.nickname }}</p>
    <p>{{ review.comment }}</p>
    <a href="{% url 'toons:review_like' review.id %}">like</a>
    {% if request.user == review.user %}
    <a href="{% url 'toons:review_update' review.id %}">edit</a>
    <a href="{% url 'toons:review_delete' review.id %}">delete</a>
    {% endif %}
    <p>Rating: {{ review.likes_count }}</p>
        </div>
    {%  for comment in review.otvet.all %}
    <div style="border: 1px solid black; margin-left: 10px;">
    <a href="{% url 'account:profile_guest' comment.user.profile.slug %}">{{comment.user.profile}}</a>
    <p>{{ comment.user.profile.nickname }}</p>
    <p>{{ comment.comment }}</p>
        </div>
    {% endfor %}
    <input id="review_input2">
    <button id="send_review" value="{{ review.id }}">send</button>

{% endfor %}
    <div>
        <input id="review_input">
        <button id="send" value="{{ toon.slug }}">send</button>
    </div>
        </div>
</body>
</html>

toons/templates/toons/toon_series.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />
</head>
<body>
<h3>{{  toon_ser.name }}</h3>
<p>{{  toon_ser.description }}</p>
<video
              id="my-video"
              class="video-js"
              controls
              preload="auto"
              width="1000"
              height="800"
              data-setup="{}"
          >
            <source src="{% url 'toons:toonseries_detaisl' toon_ser.id %}" type="video/mp4"/>
            <source src="{% url 'toons:toonseries_detaisl' toon_ser.id %}" type="video/webm"/>
          </video>
        </div>
</body>
</html>