account/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import url
from django.urls import path, include
from django.views.generic import TemplateView

from . import views
from .consumers import ChatMessagesConsumer

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('delete_message/<int:message_id>', views.delete_message, name='delete_message'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile_create/', views.create_profile, name='profile_create'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('profile_guest/<slug:slug>', views.profile_guest, name='profile_guest'),
    path('logout/', views.logout_view, name='logout'),
    path('send_friend/<slug:slug>', views.send_friend_request, name='send_friend'),
    path('accept_friend/<slug:slug>', views.accept_friend, name='accept_friend'),
    path('', views.chat, name='indsex'),
    path(r'^dialogs/$', login_required(views.DialogsView.as_view()), name='dialog'),
    path(r'^dialogs/(?P<chat_id>\d+)/$', login_required(views.MessagesView.as_view()), name='messages'),
    path(r'^dialogs/create/(?P<user_id>\d+)/$', login_required(views.CreateDialogView.as_view()), name='create_dialog'),

]

old_toon/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('toons/', include('toons.urls', namespace='toons')),
    path('account/', include('account.urls', namespace='account')),
    path('subscription/', include('subscribe_payment.urls', namespace='subscribe_payment')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toons/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, toons_detail, toons_series, get_streaming_video, category_detail, like, favorite, review, like_review, review_update,review_delete

app_name = 'toons'

urlpatterns = [
    path('', index, name='index'),
    path('<slug:slug>/', toons_detail, name='toons_detail'),
    path('series/<int:pk>/', toons_series, name='toonseries_detail'),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('toonserie/<int:pk>/', get_streaming_video, name='toonseries_detaisl'),
    path('like/<slug:slug>/', like, name='like'),
    path('favorite/<slug:slug>/', favorite, name='favorite'),
    path('review/<slug:slug>/', review, name='review'),
    path('review_likes/<int:review_id>/', like_review, name='review_like'),
    path('review_update/<int:review_id>/', review_update, name='review_update'),
    path('review_delete/<int:review_id>/', review_delete, name='review_delete'),



]

account/models.py
import random
import string
from datetime import datetime
from time import timezone

from django.db import models
from django.contrib.auth import get_user_model
from numpy import integer
from toons.models import toons_model, Review
from subscribe_payment.models import lvl_subscribe
User = get_user_model()

def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(10))

def rand_key():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(15))
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=50, unique=True, blank=True, default=rand_slug)
    nickname = models.CharField(max_length=50)
    about = models.TextField(blank=True, null=True)
    birthday = models.DateField(null=True, blank=True)
    rating = models.FloatField(default=0.0, blank=True)
    views = models.IntegerField(toons_model, default=0, blank=True, null=True)
    friends = models.ManyToManyField(to=User, related_name='friends', blank=True)
    image = models.ImageField(upload_to='profile', blank=True, default='1670311516_61-fashionhot-club-p-termobele-skins-64.jpg')
    favorites = models.ManyToManyField(to=toons_model, related_name='favorites', blank=True)
    likes_for = models.ManyToManyField(to=toons_model, related_name='likes_for', blank=True)
    likes_reviews = models.ManyToManyField(to=Review, related_name='likes_reviews', blank=True)
    sub = models.ForeignKey(lvl_subscribe, on_delete=models.CASCADE, blank=True, null=True)


    def favorite(self, toons_model):
        self.favorites.add(toons_model)
        self.favorites.add(toons_model)  # Add the toon to the user's profile

    def __str__(self):
        return self.nickname

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = rand_slug()
        super().save(*args, **kwargs)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, related_name='friend_requests_sent', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='friend_requests_received', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f"Friend Request from {self.from_user} to {self.to_user}"

    def send_request(self):
        # Логика отправки заявки
        friend_request = FriendRequest(from_user=self.from_user, to_user=self.to_user)
        friend_request.save()

    def accept_request(self, accepted=True):
        # Логика принятия заявки
        self.accepted = accepted
        self.save()
class chat_messages(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Chat(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = (
        (DIALOG, ('Dialog')),
        (CHAT, ('Chat'))
    )

    type = models.CharField(
        ('Тип'),
        max_length=1,
        choices=CHAT_TYPE_CHOICES,
        default=DIALOG
    )
    members = models.ManyToManyField(User, verbose_name=("Участник"))


    def get_absolute_url(self):
        return 'users:messages', (), {'chat_id': self.pk}


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name=("Чат"), on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name=("Пользователь"), on_delete=models.CASCADE)
    message = models.TextField(("Сообщение"))
    pub_date = models.DateTimeField(('Дата сообщения'), default=datetime.now, blank=True)
    is_readed = models.BooleanField(('Прочитано'), default=False)

    class Meta:
        ordering = ['pub_date']

    def __str__(self):
        return self.message

class notification(models.Model):
    for_user = models.ManyToManyField(User, related_name='notifications')
    not_text = models.TextField(max_length=200)
    readed = models.BooleanField(default=False)

    def __str__(self):
        return self.not_text + ' / ' + str(self.for_user)

    def readed_notification(self):
        self.readed = True
        self.save()

account/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, chat_messages

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'image', 'birthday', 'user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получите текущего пользователя
        super(ProfileForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user  # Установите текущего пользователя в качестве начального значения
            self.fields['user'].widget = forms.HiddenInput()  # Скрыть поле пользователя в форме

    def save(self, commit=True):
        user = super(ProfileForm, self).save(commit=False)
        if commit:
            user.save()
        return user

class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'image', 'birthday', 'about']
class UserForm_register(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserForm_register, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class UserForm_login(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class chat_messagesForm(ModelForm):
    class Meta:
        model = chat_messages
        fields = ['user', 'message']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получите текущего пользователя
        super(chat_messagesForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user  # Установите текущего пользователя в качестве начального значения
            self.fields['user'].widget = forms.HiddenInput()  # Скрыть поле пользователя в форме

    def save(self, commit=True):
        user = super(chat_messagesForm, self).save(commit=False)
        if commit:
            user.save()
        return user

class ChatMessage_updateForm(ModelForm):
    class Meta:
        model = chat_messages
        fields = ['user', 'message']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получите текущего пользователя
        super(ChatMessage_updateForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user  # Установите текущего пользователя в качестве начального значения
            self.fields['user'].widget = forms.HiddenInput()  # Скрыть поле пользователя в форме

    def save(self, commit=True):
        user = super(ChatMessage_updateForm, self).save(commit=False)
        if commit:
            user.save()
        return user

account/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Count
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .forms import ProfileForm, ProfileUpdateForm
from .forms import UserForm_register, UserForm_login, chat_messagesForm
from .models import Profile, FriendRequest, User, chat_messages, Chat, notification


class MessagesView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_readed=False).exclude(author=request.user).update(is_readed=True)
            else:
                chat = None
        except Chat.DoesNotExist:
            chat = None

        return render(
            request,
            'profile/messages.html',
            {
                'user_profile': request.user,
                'chat': chat,
                'chat_id': chat.id
            }
        )

class CreateDialogView(View):
    def get(self, request, user_id):
        chats = Chat.objects.filter(members__in=[request.user.id, user_id], type=Chat.DIALOG).annotate(c=Count('members')).filter(c=2)
        if chats.count() == 0:
            chat = Chat.objects.create()
            chat.members.add(request.user)
            chat.members.add(user_id)
            notif = notification.objects.create(not_text=f"Новый диалог от {request.user.username}!")
            notif.for_user.add(user_id)
        else:
            chat = chats.first()
        return redirect(reverse('account:messages', kwargs={'chat_id': chat.id}))
class DialogsView(View):
    def get(self, request):
        chats = Chat.objects.filter(members__in=[request.user.id])
        return render(request, 'profile/dialog.html', {'user_profile': request.user, 'chats': chats})
@login_required(login_url='account:login')
def create_profile(request):
    try:
        profile = request.user.profile
        # User has a profile, redirect to a specific URL
        return redirect('toons:index')
    except Profile.DoesNotExist:
        if request.method == 'POST':
            profile_form = ProfileForm(request.POST, user=request.user)  # Передайте текущего пользователя
            if profile_form.is_valid():
                profile = profile_form.save()
                return redirect('toons:index')
            # Дополнительные действия после сохранения профиля
        else:
            profile_form = ProfileForm(user=request.user)  # Передайте текущего пользователя для пустой формы

        return render(request, 'profile/profile_create.html', {'form': profile_form})
@login_required(login_url='account:login')
def profile(request):
    try:
        admin_user = User.objects.get(username=request.user.username)
        profile = Profile.objects.get(user=admin_user)
        profile_friend_requests = FriendRequest.objects.filter(to_user=profile.user)
        return render(request, 'profile/profile.html', {'profile': profile, 'profile_friend_requests': profile_friend_requests})
    except Profile.DoesNotExist:
        return redirect('account:profile_create')
@login_required(login_url='account:login')
def friend_FriendRequest(request):
    try:
        profile = request.user.profile
        return render(request, 'profile/profile.html', {'profile': profile})
    except Profile.DoesNotExist:
        return redirect('account:profile_create')

@login_required(login_url='account:login')
def profile_guest(request, slug):
    try:
        profile = Profile.objects.get(slug=slug)
        return render(request, 'profile/profile_guest.html', {'profile': profile})
    except Profile.DoesNotExist:
        return redirect('account:profile_create')
def profile_update(request):
    try:
        profile = request.user.profile
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                return redirect('account:profile')
        else:
            form = ProfileUpdateForm(instance=request.user.profile)

        return render(request, 'profile/profile_update.html', {'form': form})
    except Profile.DoesNotExist:
        return redirect('account:profile_create')

def register(request):
    form = UserForm_register(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('account:login')
    else:
        form = UserForm_register()
    return render(request, 'account/register.html', {'form': form})


def login_view(request):
    form = UserForm_login()

    if request.user.is_authenticated:
        return redirect('toons:index')

    if request.method == 'POST':

        form = UserForm_login(request.POST, request.FILES)

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('toons:index')
        else:
            return redirect('account:login')
    context = {
        'form': form
    }
    return render(request, 'account/login.html', context)




def logout_view(request):
    logout(request)
    return redirect('account:login')

def send_friend_request(request, slug, *args):
    try:
        profile = Profile.objects.get(slug=slug)
        from_user = request.user  # Get the current user sending the friend request
        to_user = profile.user  # Get the user of the profile being viewed

        friend_request = FriendRequest(from_user=from_user, to_user=to_user)
        friend_request.save()
        return redirect('account:profile')
    except ObjectDoesNotExist:
        # Обработка случая, когда профиль не существует
        return redirect('account:profile_create')

def accept_friend(request, slug, *args):
    try:
        profile = Profile.objects.get(slug=slug)
        friend_request = FriendRequest.objects.get(from_user=profile.user, to_user=request.user)
        friend_request.accept_request(
            accepted=True)  # Update the accept_request method to accept the request with status 'accepted'
        profile.friends.add(friend_request.to_user)
        friend_request.to_user.profile.friends.add(profile.user)
        friend_request.delete()
        return redirect('account:profile')
    except ObjectDoesNotExist:
        # Обработка случая, когда профиль не существует
        return redirect('account:profile_create')

def chat(request):
    user = request.user
    messages = chat_messages.objects.all()  # Initialize messages with an empty queryset
    if request.method == 'POST':
        form = chat_messagesForm(request.POST, user=user)
        if form.is_valid():
            form.save()
            # Redirect back to the same page to allow user to leave another message
            return redirect('account:chat')
    else:
        form = chat_messagesForm(user=user)
    return render(request, 'profile/chat.html', {'form': form, 'messages': messages})

def delete_message(request, message_id):
    user = request.user
    message = chat_messages.objects.get(id=message_id, user=user)
    message.delete()
    return redirect('toons:index')

account/templates/profile/chat.html
<!-- old_toon/templates/chat.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Chat Room</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>
<body>

</body>
</html>

account/templates/profile/dialog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ user_profile }}}
{%  for message in chats %}
{{message}}
<a href="{% url 'account:messages' message.pk %}">link</a>
{% endfor %}
</body>
</html>

account/templates/profile/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/chat2/'
        );

    chatSocket.onmessage = function (e) {
        document.getElementById('messages').innerHTML += e.data + '<br>'+ '<br>';
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    $(document).ready(function() {

            $('#send').click(function() {
                var message = $('#message_input').val();
                var chat = $('#send').val();
                chatSocket.send(JSON.stringify({
                    'message': message,
                    'chat': chat
                }));
                $('#message_input').val('');
            });

            $('#message_input').keyup(function(e) {
                if (e.keyCode === 13) {
                    $('#send-btn').click();
                }



            });
        }
    );





</script>
<body>
{% if chat %}
        <div id="messages" class="panel">
            <div id="innerMessages">
                {% for message in chat.message_set.all %}
                      <div class="list-group-item {% if not message.is_readed %}unreaded{% endif %}">
    <a href="#"><img class="avatar-comment"></a>
    <div class="reply-body">
        <ul class="list-inline">
            <li class="drop-left-padding">
                <strong class="list-group-item-heading"><a href="#}">{{ message.author.username }}</a></strong>
            </li>
            <li class="pull-right text-muted"><small>{{ message.pub_date }}</small></li>
        </ul>
        <div>{{ message.message|safe }}</div>
    </div>
</div>

                {% endfor %}
            </div>
        </div>
    {% endif %}
<input type="text" name="" id="message_input">
<button value="{{ chat.id }}" id="send">send</button>

</body>
</html>

account/templates/profile/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{profile.nickname}}<br>
{{profile.about}}<br>
{{profile.birthday}}<br>
{{profile.rating}}<br>
{{profile.friends.all}}<br>
<img style="width: 100px;" src="{{ profile.image.url }}" alt=""><br>
{% for toon in profile.favorites.all %}
{{toon}}<br>
{% endfor %}
{% for toon in profile.likes_for.all %}
{{toon}}<br>
{% endfor %}
<a href="{% url 'account:profile_update'%}">update</a>
<a href="{% url 'account:logout' %}">logout</a>
<a href="{% url 'account:dialog' %}">dialog</a>
<br>
    <h1>Friend Requests</h1>
    <ul>
        {% for request in profile_friend_requests %}
            <li>{{ request.from_user.profile.nickname }} wants to be your friend</li>
            <form method="post" action="{% url 'account:accept_friend' request.from_user.profile.slug %}">
                {% csrf_token %}
                <button type="submit">Accept</button>
            </form>
        {% endfor %}
    </ul>
<a href="{% url 'account:indsex' %}">122222</a>
</body>
</html>

account/templates/profile/profile_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
</body>
</html>

account/templates/profile/profile_guest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{profile}}
<a href="{% url 'account:send_friend'  profile.slug %}">send friend reqyuest</a>
<a href="{% url 'account:create_dialog' profile.user.id %}"> dialog </a>
<a href="#">chat</a>
</body>
</html>

account/templates/profile/profile_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
</body>
</html>